# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T08:49:57+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field


class CheckSpellingPostRequest(BaseModel):
    lang_code: Optional[str] = Field(None, examples=['ru'])
    text: Optional[str] = Field(None, examples=['Добрый вее!'])
